export const accountConfig = {
  title: "Accounts",
  apiEndpoint: "accounts",
  baseRoute: "accounts",
  model: "Account",
  columns: [
    { item: "accountNumber", label: "Account Number", type: "text" },
    { item: "accountName", label: "Account Name", type: "text" },
    { item: "category", label: "Category", type: "text" },
    { item: "debitAmount", label: "Debit Amount", type: "currency" },
    { item: "creditAmount", label: "Credit Amount", type: "currency" },
    { item: "balance", label: "Balance", type: "number" },
  ],
  card: [
    { item: "accountNumber", label: "Account Number", type: "text" },
    { item: "accountName", label: "Account Name", type: "text" },
    { item: "category", label: "Category", type: "text" },
    { item: "debitAmount", label: "Debit Amount", type: "currency" },
    { item: "creditAmount", label: "Credit Amount", type: "currency" },
    { item: "balance", label: "Balance", type: "number" },
  ],
  form: [
    { item: "accountNumber", label: "Account Number", type: "text" },
    { item: "accountName", label: "Account Name", type: "text" },
    { item: "category", label: "Category", type: "select" },
    { item: "debitAmount", label: "Debit Amount", type: "currency" },
    { item: "creditAmount", label: "Credit Amount", type: "currency" },
    { item: "balance", label: "Balance", type: "number" },
  ],
};
