export const budgetConfig = {
  title: "Budgets",
  apiEndpoint: "budgets",
  baseRoute: "budgets",
  model: "Budget",
  columns: [
    { item: "regNumber", label: "Budget Number", type: "text" },
    { item: "plannedPaymentDate", label: "Plan Payment Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { item: "description", label: "Description", type: "text" },
    { item: "amount", label: "Total Amount", type: "currency" },
    { item: "createdAt", label: "Created Date", type: "date" },
    { item: "updatedAt", label: "Modified Date", type: "date" },
  ],
  card: [
    { item: "regNumber", label: "Budget Number", type: "text" },
    { item: "plannedPaymentDate", label: "Plan Payment Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { item: "description", label: "Description", type: "text" },
    { item: "amount", label: "Total Amount", type: "currency" },
  ],
  form: [
    { item: "regNumber", label: "Budget Number", type: "toggle" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "amount", label: "Total Amount", type: "currency" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { item: "plannedPaymentDate", label: "Plan Payment Date", type: "date" },
    { item: "taskId", label: "Task Number", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
  ],
};
