export const clientConfig = {
  title: "Clients",
  apiEndpoint: "clients",
  baseRoute: "clients",
  model: "Client",
  columns: [
    { item: "regNumber", label: "Customer Code", type: "text" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "text" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
    { item: "category", label: "Category", type: "text" },
    { item: "country", label: "Country", type: "text" },
    { item: "taxStatus", label: "Tax Status", type: "boolean" },
  ],
  card: [
    { label: "Company Name" },
    { item: "regNumber", label: "Customer Code", type: "text" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "text" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
    { item: "legal", label: "Legal", type: "text" },
    { item: "category", label: "Category", type: "text" },
    { item: "country", label: "Country", type: "text" },
    { label: "Contact Person" },
    { item: "contactName", label: "Contact Name", type: "text" },
    { item: "contactRole", label: "Contact Role", type: "text" },
    { item: "contactPhone", label: "Contact Phone", type: "phone" },
    { item: "contactEmail", label: "Contact Email", type: "email" },
    { label: "Tax Details" },
    { item: "taxNumber", label: "Tax Number", type: "text" },
    { item: "taxAddress", label: "Tax Address", type: "text" },
    { item: "taxStatus", label: "Tax Status", type: "boolean" },
    { label: "Procurement Details" },
    { item: "procurementName", label: "Procurement Name", type: "text" },
    { item: "procurementRole", label: "Procurement Role", type: "text" },
    { item: "procurementPhone", label: "Procurement Phone", type: "phone" },
    { item: "procurementEmail", label: "Procurement Email", type: "email" },
    { item: "billingAddress", label: "Billing Address", type: "text" },
    { label: "Payment Address" },
    { item: "paymentName", label: "Payment Name", type: "text" },
    { item: "paymentRole", label: "Payment Role", type: "text" },
    { item: "paymentPhone", label: "Payment Phone", type: "phone" },
    { item: "paymentEmail", label: "Payment Email", type: "email" },
  ],
  form: [
    { item: "regNumber", label: "Customer Code", type: "toggle" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "textarea" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
    { item: "legal", label: "Legal", type: "select" },
    { item: "category", label: "Category", type: "select" },
    { item: "country", label: "Country", type: "text" },
    { item: "contactName", label: "Contact Name", type: "text" },
    { item: "contactRole", label: "Contact Role", type: "text" },
    { item: "contactPhone", label: "Contact Phone", type: "phone" },
    { item: "contactEmail", label: "Contact Email", type: "email" },
    { item: "taxNumber", label: "Tax Number", type: "text" },
    {
      item: "taxAddress",
      label: "Tax Address",
      type: "textarea",
      uppercase: true,
    },
    { item: "taxStatus", label: "Tax Status", type: "boolean" },
    { item: "procurementName", label: "Procurement Name", type: "text" },
    { item: "procurementRole", label: "Procurement Role", type: "text" },
    { item: "procurementPhone", label: "Procurement Phone", type: "phone" },
    { item: "procurementEmail", label: "Procurement Email", type: "email" },
    {
      item: "billingAddress",
      label: "Billing Address",
      type: "textarea",
      uppercase: true,
    },
    { item: "paymentName", label: "Payment Name", type: "text" },
    { item: "paymentRole", label: "Payment Role", type: "text" },
    { item: "paymentPhone", label: "Payment Phone", type: "phone" },
    { item: "paymentEmail", label: "Payment Email", type: "email" },
  ],
};
