export const contractConfig = {
  title: "Contracts",
  apiEndpoint: "contracts",
  baseRoute: "contracts",
  model: "Contract",
  columns: [
    { item: "regNumber", label: "Contract Number", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "title", label: "Title", type: "text" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "amount", label: "Amount", type: "currency" },
    { item: "signedDate", label: "Signed Date", type: "date" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "duration", label: "Duration", type: "text" },
  ],
  card: [
    { label: "Contract Details" },
    { item: "regNumber", label: "Contract Number", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "quoteNumber", label: "Quote Number", type: "text" },
    { item: "title", label: "Title", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { item: "penalty", label: "Penalty", type: "boolean" },
    { label: "Contract Customer" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "clientPicName", label: "Customer PIC Name", type: "text" },
    { item: "paymentTerm", label: "Payment Term", type: "number" },
    { label: "Contract Dates" },
    { item: "signedDate", label: "Signed Date", type: "date" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "duration", label: "Duration", type: "text" },
    { label: "Contract Amount" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "currency", label: "Currency", type: "text" },
    { item: "baseAmount", label: "Contract Amount", type: "currency" },
    { item: "exchangeRate", label: "Exchange Rate", type: "number" },
    { item: "amount", label: "Amount", type: "currency" },
  ],
  form: [
    { item: "regNumber", label: "Contract Number", type: "toggle" },
    { item: "title", label: "Title", type: "text" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "penalty", label: "Penalty", type: "boolean" },
    {
      item: "clientId",
      label: "Client Number",
      type: "select",
    },
    { item: "clientPicName", label: "Customer PIC Name", type: "text" },
    { item: "productId", label: "Product Number", type: "select" },
    { item: "paymentTerm", label: "Payment Term", type: "number" },
    { label: "Contract Amount" },
    { item: "currency", label: "Currency", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
    { label: "Quote Number" },
    { item: "quoteId", label: "Quote Number", type: "select" },
  ],
};
