export const eventConfig = {
  title: "Events",
  apiEndpoint: "events",
  baseRoute: "events",
  model: "Event",
  columns: [
    { item: "title", label: "Title", type: "text" },
    { item: "category", label: "Category", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "url", label: "Link Events", type: "text" },
  ],
  card: [
    { item: "title", label: "Title", type: "text" },
    { item: "category", label: "Category", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "url", label: "Link Events", type: "text" },
  ],
  form: [
    { item: "title", label: "Title", type: "text" },
    { item: "category", label: "Category", type: "select" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "url", label: "Link Events", type: "text" },
  ],
};
