export const fundConfig = {
  title: "FPDP",
  apiEndpoint: "funds",
  baseRoute: "funds",
  model: "Fund",
  columns: [
    { item: "regNumber", label: "FPDP Number", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { item: "amount", label: "Total Request", type: "currency" },
    { item: "expenseAmount", label: "Total Expense", type: "number" },
    { item: "balance", label: "Remaining Amount", type: "number" },
    { item: "requestDate", label: "Request Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { item: "releasedDate", label: "Released Date", type: "date" },
    { item: "expiredDate", label: "Expired Date", type: "date" },
    { item: "closedDate", label: "Closed Date", type: "date" },
    { item: "voidDate", label: "Void Date", type: "date" },
  ],
  card: [
    { label: "FPDP Details" },
    { item: "regNumber", label: "FPDP Number", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { label: "FPDP Date" },
    { item: "requestDate", label: "Request Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { item: "releasedDate", label: "Released Date", type: "date" },
    { item: "duration", label: "Duration (Days)", type: "text" },
    { item: "expiredDate", label: "Expired Date", type: "date" },
    { item: "closedDate", label: "Closed Date", type: "date" },
    { item: "voidDate", label: "Void Date", type: "date" },
    { item: "reimburseDate", label: "Reimburse Date", type: "date" },
    { item: "returnDate", label: "Return Date", type: "date" },
  ],
  form: [
    { item: "regNumber", label: "FPDP Number", type: "toggle" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "amount", label: "Total Request", type: "currency" },
    { item: "budgetId", label: "Budget Number", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
  ],
};
