export const invoiceConfig = {
  title: "Invoices",
  apiEndpoint: "invoices",
  baseRoute: "invoices",
  model: "Invoice",
  columns: [
    { item: "regNumber", label: "Invoice Number", type: "text" },
    { item: "contractTitle", label: "Contract Title", type: "text" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "productName", label: "Solution", type: "text" },
    { item: "paymentTerm", label: "Payment Term", type: "text" },
    { item: "amount", label: "Invoice Amount", type: "currency" },
    { item: "vatAmount", label: "Vat Amount", type: "currency" },
    { item: "totalAmount", label: "Total Amount", type: "currency" },
  ],
  card: [],
  form: [
    { item: "regNumber", label: "Invoice Number", type: "toggle" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "taxInvoiceNumber", label: "Tax Invoice Number", type: "text" },
    { item: "date", label: "Date", type: "date" },
    { item: "dueDate", label: "Due Date", type: "date" },
    { item: "term", label: "Term", type: "number" },
    { item: "clientNumber", label: "Client Number", type: "text" },
    { item: "clientName", label: "Customer Name", type: "text" },
    {
      item: "clientAddress",
      label: "Client Address",
      type: "textarea",
      uppercase: true,
    },
    { item: "clientPicName", label: "Client Pic Name", type: "text" },
    { item: "activityName", label: "Activity Name", type: "text" },
    { item: "paymentTerm", label: "Payment Term", type: "text" },
    { item: "amount", label: "Invoice Amount", type: "currency" },
    { item: "vatAmount", label: "Vat Amount", type: "currency" },
    { item: "totalAmount", label: "Total Amount", type: "currency" },
    { item: "emailDate", label: "Email Date", type: "email" },
    { item: "sentDate", label: "Sent Date", type: "date" },
    { item: "receiptNumber", label: "Receipt Number", type: "text" },
    { item: "deliveryType", label: "Delivery Type", type: "text" },
    { item: "receivableId", label: "Receivable Number", type: "select" },
  ],
};
