export const leadConfig = {
  title: "Leads",
  apiEndpoint: "leads",
  baseRoute: "leads",
  model: "Lead",
  columns: [
    { item: "regNumber", label: "Lead Number", type: "text" },
    { item: "leadDate", label: "Date of Contact", type: "date" },
    { item: "name", label: "Lead Name", type: "text" },
    { item: "companyName", label: "Company Name", type: "text" },
    { item: "leadSource", label: "Contact Method", type: "text" },
    { item: "productList", label: "Interested Solutions", type: "text" },
    { item: "assigneeName", label: "Assignee Name", type: "text" },
  ],
  card: [
    { label: "Lead Company" },
    { item: "companyName", label: "Company Name", type: "text" },
    { item: "companyAddress", label: "Company Address", type: "text"  },
    { item: "productList", label: "Interested Solutions", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { label: "Lead Contacts" },
    { item: "regNumber", label: "Lead Number", type: "text" },
    { item: "name", label: "Lead Name", type: "text" },
    { item: "email", label: "Email", type: "email" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "role", label: "Role", type: "text" },
    { item: "leadAddress", label: "Meeting Location", type: "text" },
    { item: "leadSource", label: "Contact Method", type: "text" },
    { item: "leadDate", label: "Date of Contact", type: "date" },
    { item: "assigneeName", label: "Assignee Name", type: "text" },
  ],
  form: [
    { item: "regNumber", label: "Lead Number", type: "toggle" },
    { label: "Potential Customer" },
    { item: "companyName", label: "Company Name", type: "text" },
    {
      item: "companyAddress",
      label: "Company Address",
      type: "textarea",
      uppercase: true,
    },
    { item: "products", label: "Interested Solutions", type: "array"},
    { item: "description", label: "Description", type: "textarea", rows: 5 },
    { label: "Initial Contact" },
    { item: "name", label: "Lead Name", type: "text" },
    { item: "email", label: "Email", type: "email" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "role", label: "Role", type: "text" },
    {
      item: "leadAddress",
      label: "Meeting Location",
      type: "textarea",
      uppercase: true,
    },
    {
      item: "leadSource",
      label: "Contact Method",
      type: "select",
      creatable: true,
    },
    { item: "leadDate", label: "Date of Contact", type: "date" },
    { item: "assigneeId", label: "Assignee Name", type: "select" },
  ],
};
