export const milestoneConfig = {
  title: "Milestones",
  apiEndpoint: "milestones",
  baseRoute: "milestones",
  model: "Milestone",
  columns: [
    { item: "order", label: "#", type: "number" },
    { item: "title", label: "Title", type: "text", width: 150 },
    { item: "share", label: "%", type: "percent", width: 70 },
    { item: "amount", label: "Amount", type: "currency", width: 100 },
    { item: "progress", label: "Progress", type: "percent", width: 100 },
    { item: "startDate", label: "Start Date", type: "date", width: 120 },
    { item: "endDate", label: "End Date", type: "date", width: 120 },
    { item: "duration", label: "Duration (Days)", type: "text", width: 100 },
    { item: "finishedDate", label: "Finished Date", type: "date", width: 100 },
  ],
  card: [
    { label: "Milestone Details" },
    { item: "order", label: "#", type: "number" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "title", label: "Title", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { item: "progress", label: "Progress", type: "percent" },
    { label: "Milestone Amount" },
    { item: "amount", label: "Amount", type: "currency" },
    { item: "share", label: "Percentage", type: "percent" },
    { label: "Milestone Date" },
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "duration", label: "Duration (Days)", type: "text" },
    { item: "finishedDate", label: "Finished Date", type: "date" },
    { item: "deliverables", label: "Deliverables", type: "text" },
  ],
  form: [
    { item: "order", label: "#", type: "number", width: 20 },
    { item: "title", label: "Title", type: "text", width: 200 },
    { item: "description", label: "Description", type: "textarea", width: 200},
    { item: "startDate", label: "Start Date", type: "date" },
    { item: "endDate", label: "End Date", type: "date" },
    { item: "share", label: "%", type: "percent", width: 60 },
    { item: "amount", label: "Amount", type: "currency", width: 200 },
    { item: "deliverables", label: "Deliverables", type: "text", width: 225 },
    { item: "assigneeId", label: "Assignee", type: "select", width: 200 },
  ],
};
