export const opportunityConfig = {
  title: "Opportunities",
  apiEndpoint: "opportunities",
  baseRoute: "opportunities",
  model: "Opportunity",
  columns: [
    { item: "regNumber", label: "Opportunity Number", type: "text" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "amount", label: "Potential Revenue", type: "currency" },
    { item: "expectedCloseDate", label: "Expected Close Date", type: "date" },
    { item: "productName", label: "Solution Name", type: "text" },
  ],
  card: [
    { label: "Opportunity Reference" },
    { item: "regNumber", label: "Opportunity Number", type: "text" },
    { item: "leadNumber", label: "Leads Number", type: "text" },
    { label: "Opportunity Details" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "expectedCloseDate", label: "Expected Close Date", type: "date" },
    { label: "Opportunity Amount", cols: 4 },
    { item: "currency", label: "Currency", type: "text" },
    { item: "baseAmount", label: "Amount", type: "number" },
    { item: "exchangeRate", label: "Exchange Rate", type: "number" },
    { item: "amount", label: "Potential Revenue", type: "currency" },
  ],
  form: [
    { item: "regNumber", label: "Opportunity Number", type: "toggle" },
    { label: "Opportunity Details" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "productId", label: "Solution Name", type: "select" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "expectedCloseDate", label: "Expected Close Date", type: "date" },
    { label: "Opportunity Amount" },
    { item: "currency", label: "Currency", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
    { label: "Lead Number" },
    { item: "leadId", label: "Lead Number", type: "select" },
  ],
};
