export const purchaseConfig = {
  title: "Purchases",
  apiEndpoint: "purchases",
  baseRoute: "purchases",
  model: "Purchase",
  columns: [
    { item: "regNumber", label: "PO Number", type: "text" },
    { item: "date", label: "Date", type: "date" },
    { item: "dueDate", label: "Due Date", type: "date" },
    { item: "description", label: "Description", type: "text" },
    { item: "amount", label: "Amount", type: "currency" },
    { item: "vatAmount", label: "Vat Amount", type: "currency" },
    { item: "totalAmount", label: "Total Amount", type: "currency" },
  ],
  card: [
    { item: "regNumber", label: "PO Number", type: "text" },
    { item: "date", label: "Date", type: "date" },
    { item: "dueDate", label: "Due Date", type: "date" },
    { item: "description", label: "Description", type: "text" },
    { item: "amount", label: "Amount", type: "currency" },
    { item: "vatAmount", label: "Vat Amount", type: "currency" },
    { item: "totalAmount", label: "Total Amount", type: "currency" },
  ],
  form: [
    { item: "regNumber", label: "PO Number", type: "toggle" },
    { item: "date", label: "Date", type: "date" },
    { item: "dueDate", label: "Due Date", type: "date" },
    { item: "description", label: "Description", type: "textarea" },
    { item: "amount", label: "Amount", type: "currency" },
    { item: "vatAmount", label: "Vat Amount", type: "currency" },
    { item: "totalAmount", label: "Total Amount", type: "currency" },
  ],
};
