export const quoteConfig = {
  title: "Quotes",
  apiEndpoint: "quotes",
  baseRoute: "quotes",
  model: "Quote",
  columns: [
    { item: "regNumber", label: "Quote Number", type: "text" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "amount", label: "Quotation Amount", type: "currency" },
    { item: "releasedDate", label: "Released Date", type: "date" },
    { item: "expiredDate", label: "Expired Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
  ],
  card: [
    { label: "Quotes Reference" },
    { item: "regNumber", label: "Quote Number", type: "text" },
    { item: "opportunityNumber", label: "Opportunity Number", type: "text" },
    { label: "Quotes Details" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "description", label: "Description", type: "text" },
    { label: "Quotes Date" },
    { item: "releasedDate", label: "Released Date", type: "date" },
    { item: "expiredDate", label: "Expired Date", type: "date" },
    { item: "approvedDate", label: "Approved Date", type: "date" },
    { label: "Quotation Amount", cols: 4 },
    { item: "currency", label: "Currency", type: "text" },
    { item: "baseAmount", label: "Amount", type: "number" },
    { item: "exchangeRate", label: "Exchange Rate", type: "number" },
    { item: "amount", label: "Quotation Amount", type: "currency" },
  ],
  form: [
    { item: "regNumber", label: "Quote Number", type: "toggle" },
    { label: "Quotes Details" },
    { item: "title", label: "Title", type: "text" },
    { item: "company", label: "Company", type: "text" },
    { item: "productId", label: "Solution Name", type: "select" },
    { item: "description", label: "Description", type: "textarea" },
    { label: "Quotation Amount" },
    { item: "currency", label: "Currency", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
    { label: "Opportunity Number" },
    { item: "opportunityId", label: "Opportunity Number", type: "select" },
  ],
};
