export const receivableConfig = {
  title: "Receivables",
  apiEndpoint: "receivables",
  baseRoute: "receivables",
  model: "Receivable",
  columns: [
    { item: "regNumber", label: "AR Number", type: "text" },
    { item: "milestoneTitle", label: "Milestone Title", type: "text" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "paymentTerm", label: "Payment Term", type: "text" },
    {
      item: "estimatedInvReleaseDate",
      label: "Est Inv Release Date",
      type: "text",
    },
    {
      item: "invoiceReleasedDate",
      label: "Invoice Released Date",
      type: "text",
    },
    { item: "invoiceNumber", label: "Invoice Number", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "invoiceAmount", label: "Billed Amount", type: "text" },
    { item: "invoiceVatAmount", label: "VAT Amount", type: "text" },
    { item: "contractAmount", label: "Contract Amount", type: "text" },
    { item: "contractDate", label: "Contract Date", type: "date" },
  ],
  card: [
    { label: "AR Details" },
    { item: "regNumber", label: "AR Number", type: "text" },
    { item: "clientName", label: "Customer Name", type: "text" },
    { item: "productName", label: "Solution Name", type: "text" },
    { item: "milestoneTitle", label: "Milestone Title", type: "text" },
    { item: "paymentTerm", label: "Payment Term", type: "text" },
    { item: "contractNumber", label: "Contract Number", type: "text" },
    { label: "Invoice Details" },
    { item: "invoiceNumber", label: "Invoice Number", type: "text" },
    {
      item: "estimatedInvReleaseDate",
      label: "Est Inv Release Date",
      type: "text",
    },
    {
      item: "invoiceReleasedDate",
      label: "Invoice Released Date",
      type: "text",
    },
    { item: "dueDate", label: "Due Date", type: "date" },
    { item: "balance", label: "Balance", type: "currency" },
    { item: "actualPaymentDate", label: "Payment Date", type: "text" },
    { item: "projectNumber", label: "Project Number", type: "text" },
    { item: "contractAmount", label: "Contract Amount", type: "text" },
    { item: "contractDate", label: "Contract Date", type: "date" },
    { item: "paidAmount", label: "Amount Paid", type: "text" },
  ],
  form: [
    { item: "regNumber", label: "AR Number", type: "toggle" },
    { item: "milestoneId", label: "Milestone Number", type: "select" },
    { item: "assigneeId", label: "Assignee", type: "select" },
  ],
};
