export const taskConfig = {
  title: "Tasks",
  apiEndpoint: "tasks",
  baseRoute: "tasks",
  model: "Task",
  columns: [
    { item: "milestoneTitle", label: "Milestone", type: "text" },
    { item: "order", label: "#", type: "number" },
    { item: "title", label: "Title", type: "text" },
    { item: "share", label: "Percentage", type: "percent" },
    { item: "amount", label: "Budget Amount", type: "currency" },
    { item: "plannedStartDate", label: "Planned Start Date", type: "date" },
    { item: "plannedEndDate", label: "Planned End Date", type: "date" },
    { item: "actualStartDate", label: "Actual Start Date", type: "date" },
    { item: "actualEndDate", label: "Actual End Date", type: "date" },
    { item: "metrics", label: "Metrics", type: "text" },
    { item: "progress", label: "Progress", type: "percent" },
  ],
  card: [
    { label: "Task Details" },
    { item: "title", label: "Title", type: "text" },
    { item: "share", label: "Percentage", type: "percent" },
    { item: "amount", label: "Budget Amount", type: "currency" },
    { item: "metrics", label: "Metrics", type: "text" },
    { item: "progress", label: "Progress", type: "percent" },
    { item: "remarks", label: "Remarks", type: "text" },
    { label: "Task Date" },
    { item: "plannedStartDate", label: "Planned Start Date", type: "date" },
    { item: "plannedEndDate", label: "Planned End Date", type: "date" },
    { item: "actualStartDate", label: "Actual Start Date", type: "date" },
    { item: "actualEndDate", label: "Actual End Date", type: "date" },
  ],
  form: [
    { item: "order", label: "#", type: "number", width: 20  },
    { item: "title", label: "Title", type: "text" },
    { item: "share", label: "%", type: "percent", width: 60  },
    { item: "amount", label: "Budget Amount", type: "currency" },
    { item: "plannedStartDate", label: "Planned Start Date", type: "date" },
    { item: "plannedEndDate", label: "Planned End Date", type: "date" },
    { item: "actualStartDate", label: "Actual Start Date", type: "date" },
    { item: "actualEndDate", label: "Actual End Date", type: "date" },
    { item: "metrics", label: "Metrics", type: "text" },
    { item: "remarks", label: "Remarks", type: "text" },
    { item: "assigneeId", label: "Assignee", type: "select" },
  ],
};
