export const taxDocumentConfig = {
  title: "TaxDocuments",
  apiEndpoint: "taxdocuments",
  baseRoute: "taxdocuments",
  model: "TaxDocument",
  columns: [
    { item: "date", label: "Tanggal Bukti Potong", type: "date" },
    { item: "taxDeductionNumber", label: "No. Bukti Potong", type: "text" },
    { item: "taxPeriod", label: "Masa Pajak", type: "text" },
    { item: "taxObjectCode", label: "Kode Objek Pajak", type: "text" },
    { item: "amount", label: "Dasar Pengenaan Pajak", type: "currency" },
    { item: "vatAmount", label: "PPh Dipotong", type: "currency" },
  ],
  card: [
    { item: "date", label: "Tanggal Bukti Potong", type: "date" },
    { item: "taxDeductionNumber", label: "No. Bukti Potong", type: "text" },
    { item: "taxPeriod", label: "Masa Pajak", type: "text" },
    { item: "taxObjectCode", label: "Kode Objek Pajak", type: "text" },
    { item: "amount", label: "Dasar Pengenaan Pajak", type: "currency" },
    { item: "vatAmount", label: "PPh Dipotong", type: "currency" },
  ],
  form: [
    { item: "date", label: "Tanggal Bukti Potong", type: "date" },
    { item: "taxDeductionNumber", label: "No. Bukti Potong", type: "text" },
    { item: "taxPeriod", label: "Masa Pajak", type: "text" },
    { item: "taxObjectCode", label: "Kode Objek Pajak", type: "text" },
    { item: "amount", label: "Dasar Pengenaan Pajak", type: "currency" },
    { item: "vatAmount", label: "PPh Dipotong", type: "currency" },
    { item: "receivableId", label: "Receivable Number", type: "select" },
  ],
};
