export const vendorConfig = {
  title: "Vendors",
  apiEndpoint: "vendors",
  baseRoute: "vendors",
  model: "Vendor",
  columns: [
    { item: "regNumber", label: "Vendor Code", type: "text" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "text" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
  ],
  card: [
    { label: "Company Name" },
    { item: "regNumber", label: "Vendor Code", type: "text" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "text" },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
    { item: "legal", label: "Legal", type: "text" },
    { item: "productType", label: "Product Type", type: "text" },
    { label: "Contact Person" },
    { item: "contactName", label: "Contact Name", type: "text" },
    { item: "contactRole", label: "Contact Role", type: "text" },
    { item: "contactPhone", label: "Contact Phone", type: "phone" },
    { item: "contactEmail", label: "Contact Email", type: "email" },
  ],
  form: [
    { item: "regNumber", label: "Vendor Code", type: "toggle" },
    { item: "name", label: "Name", type: "text" },
    { item: "address", label: "Address", type: "textarea", uppercase: true },
    { item: "phone", label: "Phone", type: "phone" },
    { item: "email", label: "Email", type: "email" },
    { item: "legal", label: "Legal", type: "select" },
    { item: "productType", label: "Product Type", type: "text" },
    { item: "contactName", label: "Contact Name", type: "text" },
    { item: "contactRole", label: "Contact Role", type: "text" },
    { item: "contactPhone", label: "Contact Phone", type: "phone" },
    { item: "contactEmail", label: "Contact Email", type: "email" },
  ],
};
